# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1411484988);
user_pref("app.update.lastUpdateTime.background-update-timer", 1411456737);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1411485108);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1411488348);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1411484868);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1411478217);
user_pref("browser.backspace_action", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtab.url", "http://www.google.com");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.defaultenginename", "Google Default");
user_pref("browser.search.selectedEngine", "Google Default");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140825202822");
user_pref("browser.slowStartup.averageTime", 4366);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.page", 3);
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4,\"passwords\":0}");
user_pref("datareporting.healthreport.currentDaySubmissionFailureCount", 2);
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1411485830063");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1411485748771");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1411489430064");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1411465191143");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1411468807778");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1411393061977");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4388);
user_pref("datareporting.sessions.current.main", 942);
user_pref("datareporting.sessions.current.sessionRestored", 6451);
user_pref("datareporting.sessions.current.startTime", "1411484626026");
user_pref("datareporting.sessions.current.totalTime", 4545);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.prunedIndex", 7);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"langpack-ja@firefox.mozilla.org\":{\"version\":\"32.0\",\"type\":\"locale\",\"descriptor\":\"/opt/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1411393663);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-ja@firefox.mozilla.org\":{\"descriptor\":\"/opt/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\",\"mtime\":1409038872000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/opt/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411393045000,\"rdfTime\":1409033418000}}}]");
user_pref("extensions.lastAppVersion", "32.0");
user_pref("extensions.lastPlatformVersion", "32.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("font.name.serif.x-western", "Monaco");
user_pref("gecko.buildID", "20140825202822");
user_pref("gecko.mstone", "32.0");
user_pref("idle.lastDailyNotification", 1411484929);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1411484696);
user_pref("places.history.expiration.transient_current_max_pages", 52782);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1411396040);
user_pref("toolkit.startup.last_success", 1411484626);
user_pref("toolkit.telemetry.previousBuildID", "20140825202822");
