# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1411393662);
user_pref("app.update.lastUpdateTime.background-update-timer", 1411456737);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1411393782);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1411460097);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1411393542);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1411456617);
user_pref("browser.backspace_action", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtab.url", "http://www.google.com");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.defaultenginename", "Google Default");
user_pref("browser.search.selectedEngine", "Google Default");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140825202822");
user_pref("browser.slowStartup.averageTime", 4225);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.page", 3);
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4,\"passwords\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1411479461978");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1411459746061");
user_pref("datareporting.policy.firstRunTime", "1411393061977");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 4581);
user_pref("datareporting.sessions.current.main", 932);
user_pref("datareporting.sessions.current.sessionRestored", 6890);
user_pref("datareporting.sessions.current.startTime", "1411465123412");
user_pref("datareporting.sessions.current.totalTime", 32);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1411393060607,\"a\":213,\"t\":3672,\"c\":true,\"m\":52,\"fp\":5530,\"sr\":6769}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1411396735759,\"a\":1,\"t\":16,\"c\":false,\"m\":122,\"fp\":6421,\"sr\":3797}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1411407354806,\"a\":51,\"t\":1850,\"c\":true,\"m\":1033,\"fp\":3935,\"sr\":5520}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1411433572162,\"a\":0,\"t\":7,\"c\":false,\"m\":941,\"fp\":4418,\"sr\":6185}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1411456374639,\"a\":46,\"t\":860,\"c\":true,\"m\":1077,\"fp\":4520,\"sr\":6452}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1411457237414,\"a\":33,\"t\":2312,\"c\":true,\"m\":82,\"fp\":2235,\"sr\":3902}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1411459677449,\"a\":2,\"t\":723,\"c\":true,\"m\":1077,\"fp\":4568,\"sr\":6676}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-ja@firefox.mozilla.org\":{\"version\":\"32.0\",\"type\":\"locale\",\"descriptor\":\"/opt/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1411393663);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-ja@firefox.mozilla.org\":{\"descriptor\":\"/opt/firefox/browser/extensions/langpack-ja@firefox.mozilla.org.xpi\",\"mtime\":1409038872000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/opt/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411393045000,\"rdfTime\":1409033418000}}}]");
user_pref("extensions.lastAppVersion", "32.0");
user_pref("extensions.lastPlatformVersion", "32.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("font.name.serif.x-western", "Monaco");
user_pref("gecko.buildID", "20140825202822");
user_pref("gecko.mstone", "32.0");
user_pref("idle.lastDailyNotification", 1411396040);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1411396040);
user_pref("places.history.expiration.transient_current_max_pages", 52782);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1411396040);
user_pref("toolkit.startup.last_success", 1411465124);
user_pref("toolkit.telemetry.previousBuildID", "20140825202822");
