#!/bin/sh
set -e

FLAVOR=$1
PACKAGE=trr22

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}
files="trr.el trr-sess.el trr-mesg.el trr-menus.el trr-graphs.el trr-files.el"
flags="-batch --no-site-file -l path.el -f batch-byte-compile"

if [ ${FLAVOR} = "emacs22" -o ${FLAVOR} = "emacs-snapshot" -o ${FLAVOR} = "emacs23" ] ; then 
  echo install/${PACKAGE}: Byte-compiling for ${FLAVOR}
  install -m 755 -d ${ELCDIR}
  cd ${ELDIR}
  cp ${files} ${ELCDIR}
  cd ${ELCDIR}
  cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
  ${FLAVOR} ${flags} ${files}
  rm -f *.el path.el*
fi
exit 0;
