#! /bin/sh
#                               -*- Mode: Sh -*- 
# postinst --- 
# Author           : Manoj Srivastava ( srivasta@tiamat.datasync.com ) 
# Created On       : Thu Oct 15 00:23:39 1998
# Created On Node  : tiamat.datasync.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Thu Dec  2 15:21:12 1999
# Last Machine Used: glaurung.green-gryphon.com
# Update Count     : 6
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# 
# 


# Abort if any command returns an error value
set -e

package_name=trr22


# This script is called as the last step of the installation of the
# package.  All the package's files are in place, dpkg has already done
# its automatic conffile handling, and all the packages we depend of
# are already fully installed and configured.

# The following idempotent stuff doesn't generally need protecting
# against being run in the abort-* cases.

# Install info files into the dir file
#install-info --quiet --section "Emacs" "Emacs" \
#              --description="The news reader Gnus." /usr/share/info/gnus.gz

# Ensure the menu system is updated
[ ! -x /usr/bin/update-menus ] || /usr/bin/update-menus

case "$1" in
  configure)
    # Configure this package.  If the package must prompt the user for
    # information, do it here.
    :
    if [ -x  /usr/lib/emacsen-common/emacs-package-install ]; then
	/usr/lib/emacsen-common/emacs-package-install $package_name
    fi

    # There are three sub-cases:
    if test "${2+set}" != set; then
      # We're being installed by an ancient dpkg which doesn't remember
      # which version was most recently configured, or even whether
      # there is a most recently configured version.
      :

    elif test -z "$2" -o "$2" = "<unknown>"; then
      # The package has not ever been configured on this system, or was
      # purged since it was last configured.
      :

    else
      # Version $2 is the most recently configured version of this
      # package.
      :

    fi ;;

  abort-upgrade)
    # Back out of an attempt to upgrade this package FROM THIS VERSION
    # to version $2.  Undo the effects of "prerm upgrade $2".
    :

    ;;
  abort-remove)
    if test "$2" != in-favour; then
      echo "$0: undocumented call to \`postinst $*'" 1>&2
      exit 0
    fi
    # Back out of an attempt to remove this package, which was due to
    # a conflict with package $3 (version $4).  Undo the effects of
    # "prerm remove in-favour $3 $4".
    :

    ;;
  abort-deconfigure)
    if test "$2" != in-favour -o "$5" != removing; then
      echo "$0: undocumented call to \`postinst $*'" 1>&2
      exit 0
    fi
    # Back out of an attempt to deconfigure this package, which was
    # due to package $6 (version $7) which we depend on being removed
    # to make way for package $3 (version $4).  Undo the effects of
    # "prerm deconfigure in-favour $3 $4 removing $6 $7".
    :

    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

#if command -v install-docs >/dev/null 2>&1; then
#  install-docs -i /usr/share/doc-base/$package_name
#fi

exit 0
